//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSoft2.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatriculaCurso
    {
        public int Id { get; set; }
        public int IdUsuario { get; set; }
        public int IdCurso { get; set; }
        public int IdCentro { get; set; }
        public bool Estado { get; set; }
        public bool EsAlumno { get; set; }
    
        public virtual Centros Centros { get; set; }
        public virtual Cursos Cursos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
