//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSoft2.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreguntasPorPrueba
    {
        public int Id { get; set; }
        public int IdPrueba { get; set; }
        public int IdPregunta { get; set; }
        public bool Estado { get; set; }
    
        public virtual Preguntas Preguntas { get; set; }
        public virtual Pruebas Pruebas { get; set; }
    }
}
